services:
  - type: web
    name: cal.com
    env: node
    plan: free # Or your desired plan
    buildCommand: "yarn && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: calcom-db
          property: connectionString
      - key: NEXTAUTH_URL
        generateValue: true
      - key: NEXT_PUBLIC_WEBAPP_URL
        sync: false
        value: ${process.env.RENDER_EXTERNAL_URL}
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: CALENDSO_ENCRYPTION_KEY
        generateValue: true
      - key: NODE_VERSION
        value: 18.17.1
      - key: YARN_VERSION
        value: 3.4.1

  - type: psql
    name: calcom-db
    plan: free # Or your desired plan
    version: "14"