services:
  - type: web
    name: cal.com
    env: node
    plan: free # Or your desired plan
    # Run Prisma migrations before build to ensure DB schema exists at runtime
    buildCommand: "yarn install && yarn workspace @calcom/prisma db-deploy && yarn build"
    startCommand: "yarn start"
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        fromService:
          type: psql
          name: calcom-db
          property: connectionString
      - key: NEXTAUTH_URL
        generateValue: true
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: UBlAFO/oFiqBdoYLn7YCwaWQ+l0/wdz2WEDUvdSNYSk=
        generateValue: true
      - key: NODE_VERSION
        value: 18.17.1
      - key: YARN_VERSION
        value: 3.4.1

  - type: psql
    name: calcom-db
    plan: free # Or your desired plan
    version: "14"
